### ISSUE TITLE
Google places reviews as source

### ISSUE THREAD

**Issue by lalitpagaria** [obsei/obsei#104]
Supporting links -
https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews/list
https://developers.google.com/my-business/content/review-data#list_all_reviews
https://developers.google.com/my-business/reference/rest/#collection-v3accountslocationsreviews

For Crawler -
Yet to find

**Comment by shahrukhx01** [comment]
How about if we write the python equivalent of this?
[https://github.com/drobnikj/crawler-google-places](https://github.com/drobnikj/crawler-google-places)

**Comment by lalitpagaria** [comment]
I haven't encountered any python package (which does not use selenium or scrapy). Not sure if we can achieve google places review crawling without selenium and scrapy. First level we can simply target Google places reviews (not search capability)

Like user will share this link
https://www.google.com/maps/place/Google/@40.7414728,-74.0055813,17z/data=!4m7!3m6!1s0x89c259bf5c1654f3:0xc80f9cfce5383d5d!8m2!3d40.7414688!4d-74.0033873!9m1!1b1

We parse it (these are equivalent java script code)
https://github.com/drobnikj/crawler-google-places/search?q=reviews
