### ISSUE TITLE
[BUG] google_news_example.py is not working 

### ISSUE THREAD

**Issue by edumagol** [obsei/obsei#172]
**Describe the bug**
When I tried to run the google_news_example.py I got an error message as the picture attached.

**To Reproduce**
Steps to reproduce the behavior: run the google_news_example.py

**Expected behavior**
Run the file and see the response /output of the example.

**Stacktrace**
If applicable, add stacktrace to help explain your problem.

**Please complete the following information:**
 - OS: Windows
 - Version: 10
<img width="852" alt="pbsei_bug" src="https://user-images.githubusercontent.com/22715100/126700440-66d97801-9333-4895-8f63-e00f9025c345.png">

**Additional context**

**Comment by lalitpagaria** [comment]
@edumagol Thank you for reporting this. Web crawler failed to fetch paywalled article and there was missing None check.
I have fixed this issue. Kindly try latest master branch to test it out.

**Comment by edumagol** [comment]
Hi @lalitpagaria , sure! Thanks for the rapid response and also for fixing it. I will try it now and ASAP give you a feedback. All the best, Edu. 

P.S. - congrats for the awesome work at obsei!
