### ISSUE TITLE
[BUG] google_news_example.py is not working with two terms in the query's string

### ISSUE THREAD

**Issue by edumagol** [obsei/obsei#174]
**Describe the bug**
When I tried to use query = "Inteligência artificial" (which means Artificial intelligence in portuguese, I got the error message as can be seen in the picture attached.

**To Reproduce**
Steps to reproduce the behavior: run google_news_example.py with query = "Inteligência artificial"

**Expected behavior**
Both terms can be searched with the google news crawler
**Stacktrace**
If applicable, add stacktrace to help explain your problem.

**Please complete the following information:**
 - OS: Windows
 - Version: 10
<img width="1280" alt="obsei_bug" src="https://user-images.githubusercontent.com/22715100/126790519-6b7b3d3f-a0bb-4bd0-8bf2-5146fd30d389.png">

**Additional context**

**Comment by edumagol** [comment]
Hi @lalitpagaria , found one way to solve that: i believe it is because of the pT language accents, like hte use of ^ character, we got the error... when I try Inteligencia Artificial it worked. So, maybe it can have an improvement concerning the ASCII format or other that can handle other languages in the query string.

**Comment by lalitpagaria** [comment]
@edumagol Thank you for reporting it. 
I am currently running low in bandwidth, it would take some time to fix it.
I think you have rightly found the issue, so would you like to raise a PR to fix it?
I feel we might need to encode query to something similar https://www.kite.com/python/docs/urllib.parse.quote

**Comment by edumagol** [comment]
Hi @lalitpagaria , thanks! I can try, I am not an experienced developer, but I would to try to help. I will take a look on that and try to fix it. If it works, I will let you know and hopefully can do a PR. Anyway, thanks for the opportunity. All the best!

**Comment by lalitpagaria** [comment]
@edumagol We have fixed the issue. Could you please check latest changes and let us know.
