### ISSUE TITLE
[BUG] Not able to use Twitter and Facebook as Data Source

### ISSUE THREAD

**Issue by tanish36** [obsei/obsei#188]
**Describe the bug**
Whenever i try to import the library required to use twiiter and facebook it throws the error "consumer_key and consumer_secret required to generate bearer_token via Twitter" and that only just by loading the library.

**To Reproduce**

!pip install git+https://github.com/lalitpagaria/obsei.git
from obsei.source.twitter_source import TwitterCredentials, TwitterSource, TwitterSourceConfig

**Expected behavior**
To import the library and pass the credential later on.

**Stacktrace**
AttributeError                            Traceback (most recent call last)
<ipython-input-2-84b986621fdc> in <module>()
----> 1 from obsei.source.twitter_source import TwitterCredentials, TwitterSource, TwitterSourceConfig

2 frames
/usr/local/lib/python3.7/dist-packages/obsei/source/twitter_source.py in __init__(self, **data)
     85             if self.consumer_key is None and self.consumer_secret is None:
     86                 raise AttributeError(
---> 87                     "consumer_key and consumer_secret required to generate bearer_token via Twitter"
     88                 )
     89 

AttributeError: consumer_key and consumer_secret required to generate bearer_token via Twitter

**Please complete the following information:**
 - OS: Google Colab

**Additional context**
Installed the obsei using thi command : !pip install git+https://github.com/lalitpagaria/obsei.git

**Comment by lalitpagaria** [comment]
@tanish36 Thanks for reporting this. This is regression caused by this commit https://github.com/obsei/obsei/commit/62d3d79dc284aac7f36620884bc804fe0814c310
I have reverted the changes in this PR https://github.com/obsei/obsei/pull/189
Please check now and let us know
