### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sumitkumar2000** [obsei/obsei#197]
**Describe the bug**
Unable to create source_response_list for twitter

**Expected behavior**
Want to fetch tweets and all metadata in source_response_list

**Stacktrace**
09/28/2021 02:01:41 - ERROR - searchtweets.result_stream -   Rate limit hit... Will retry...
09/28/2021 02:01:41 - ERROR - searchtweets.result_stream -   Will retry in 36 seconds...
09/28/2021 02:02:17 - ERROR - searchtweets.result_stream -    HTTP Error code: 429: Rate limit exceeded
 | Too Many Requests

**Please complete the following information:**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by lalitpagaria** [comment]
@sumitkumar2000 Twitter recently changed their message format which caused this issue. I am trying to fix this, but due to my twitter API monthly limit unable to test the changes out. Can you please test changed from this PR https://github.com/obsei/obsei/pull/198
