### ISSUE TITLE
[BUG]TwitterSourceConfig - AttributeError: At least one non empty parameter required (query, keywords, hashtags, and usernames)

### ISSUE THREAD

**Issue by chxlium** [obsei/obsei#243]
`source_config = TwitterSourceConfig(
    usernames=["@Zappos"],
    lookup_period="24h",
    tweet_fields=[.....
`

error:

> AttributeError: At least one non empty parameter required (query, keywords, hashtags, and usernames)

**The bug is in the TwitterSource class**

    def lookup(self, config: TwitterSourceConfig, **kwargs) -> List[TextPayload]:  # type: ignore[override]
        if (
            not config.query
            and not config.keywords
            and not config.hashtags
            and config.usernames
        ):

it should be 

    def lookup(self, config: TwitterSourceConfig, **kwargs) -> List[TextPayload]:  # type: ignore[override]
        if (
            not config.query
            and not config.keywords
            and not config.hashtags
            and not config.usernames
        ):

**Comment by lalitpagaria** [comment]
@chxlium Thank you for reporting this. I will check and let you know.

**Comment by chxlium** [comment]
@lalitpagaria cool thanks!
One irrelevant question, how can I set proxy, for example, in Google news scaper?

**Comment by chxlium** [comment]
@lalitpagaria Oh yeah that would be great!

**Comment by lalitpagaria** [comment]
Fixed with #246
