### ISSUE TITLE
UNNABLE to import NER ANALYZER  not found .   

### ISSUE THREAD

**Issue by juancho-debug** [obsei/obsei#297]
Hello im sorry that i dont have the tecnical abilities to understand the problem . 
Im running the NERAnalyzer in a python proyect in visual studio .   In linux debian . and the other analyzers work perfectly . But   it seams that it does not recognize the import . 

  File "/home/pancho/PROGRAMACION/FLUJOS_PRUEBAS_OBSEI/main.py", line 3, in <module>
    from obsei.analyzer.ner_analyzer import NERAnalyzer
ImportError: cannot import name 'NERAnalyzer' from 'obsei.analyzer.ner_analyzer' (/home/pancho/.local/lib/python3.11/site-packages/obsei/analyzer/ner_analyzer.py)

And  Im just doing as the documentation says i think . from obsei.analyzer.ner_analyzer import NERAnalyzer

# NER analyzer does not need configuration settings
analyzer_config=None

# initialize ner analyzer
# For supported models refer https://huggingface.co/models?filter=token-classification
text_analyzer = NERAnalyzer(
   model_name_or_path="elastic/distilbert-base-cased-finetuned-conll03-english",
   device = "auto"
)

It seams that its already installed but is not detecting it , somehow   :    
after a pip3 install obsei[NERAnalyzer]
  Requirement already satisfied: obsei[NERAnalyzer] in /home/pancho/.local/lib/python3.11/site-packages (0.0.14)
WARNING: obsei 0.0.14 does not provide the extra 'neranalyzer'´

If this is a silly mistake made by me , im sorry to disturb .  
THANKS ANYWAY .

**Comment by lalitpagaria** [comment]
@juancho-debug Sorry for late response. You need to correct import statement -
```
from obsei.analyzer.ner_analyzer import TransformersNERAnalyzer
```
