### ISSUE TITLE
[BUG] Runtime error Demo version .

### ISSUE THREAD

**Issue by tanersekmen** [obsei/obsei#308]
There is an error on the demo version. 
You can check from this image: 

<img width="1285" alt="Screen Shot 2023-10-17 at 13 37 35" src="https://github.com/obsei/obsei/assets/56790802/1f76f968-4e9c-4a14-8023-b8f33ded20e8">

**Comment by xuhaoteoh** [comment]
Encountered the same problem today. 
<img width="955" alt="image" src="https://github.com/obsei/obsei/assets/56465408/4b67adcd-8218-48ff-8af5-f119209820d0">

**Comment by lalitpagaria** [comment]
Thanks @xuhaoteoh and @tanersekmen for reporting this issue. Currently both (@GirishPatel and @lalitpagaria) the maintainers are busy with something. Would you like to work on fixing it, we will guide you.

**Comment by tanersekmen** [comment]
@lalitpagaria thank you for your message :)

**Comment by lalitpagaria** [comment]
@xuhaoteoh and @tanersekmen please check now as we have fixed the issue with HF space obsei app.

**Comment by tanersekmen** [comment]
Hello Lalit, when I checked the Obsei app, there was no problem. Thank you so much for your interest.
