### ISSUE TITLE
[Analyzer] Integrate intent classifier

### ISSUE THREAD

**Issue by lalitpagaria** [obsei/obsei#77]
An intent classifier is useful to detect what customer goals like buy, sell, and purchase also useful in conversional flow. 

This same things can also be done via zero shot classifier as well but it would better to add separate analyzer to separate it from generic text classification. It will help user to load their own models for this purpose.

**Comment by lalitpagaria** [comment]
@shahrukhx01 Do you have experience about it? Main idea to find what user want when he/she raise wrote message on social media or email etc? More specific fine tuned model for this would be great as zero shot will not work as expected.
It could be the one you suggested for crypto currency.

**Comment by shahrukhx01** [comment]
@lalitpagaria sure, I can finetune a transformer for this. But I will first have to curate a dataset for this.

**Comment by shahrukhx01** [comment]
@lalitpagaria we can also use this dataset along sentiment analyzer to determine happiness: https://github.com/TZstatsADS/Fall2018-Proj1-AlexYH-Chen?utm_source=catalyzex.com
